version: '3.7'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=SENHA ## ---> SENHA DO POSTGRES <--- ##
    networks:
      - NOME_DA_REDE ## ---> NOME DA REDE INTERNA  <--- ##
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

  redis:
    image: redis:latest
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379"
      ]
    volumes:
      - redis_data:/data
    networks:
      - $nome_rede_interna
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

volumes:
  postgres_data:
    external: true
    name: postgres_data
  redis_data:
    external: true
    name: redis_data

networks:
  NOME_DA_REDE: ## ---> NOME DA REDE INTERNA  <--- ##
    external: true
    name: NOME_DA_REDE ## ---> NOME DA REDE INTERNA  <--- ##
